### ISSUE TITLE
Cannot use string fields for rows

### ISSUE THREAD

**Issue by Sejsel** [boazreicher/mosaic-plot#2]
I am trying to use the plugin to visualise some simple data, but it doesn't seem to be finding String fields for the row breakdown.

This seems to be caused by the plugin looking for some kind of labels instead of real fields. The labels seem to be some kind of obscure feature that is not even documented by grafana beyond [this](https://grafana.com/docs/grafana/latest/packages_api/data/labels/) and there doesn't seem to be any way to set them using my data source.

The documentation of this plugin mentions that fields and makes no mention of labels [here](https://boazreicher.github.io/mosaic-plot/configuration_options/) and in the screenshot. On the other hand, [this page](https://boazreicher.github.io/mosaic-plot/data/) does mention labels but doesn't say what they are.

It would be very nice to have an option to use proper fields instead of some obscure labels.

![image](https://user-images.githubusercontent.com/998408/166290969-3dccb76a-36d0-4515-a4fe-c00f772c0d9f.png)
![image](https://user-images.githubusercontent.com/998408/166291013-0f57cf5d-fce6-494c-9a1b-2f2f8c124649.png)

**Comment by boazreicher** [comment]
I think you can make it work by adding a adding a "Prepare time series" transform (use "multi-frame time series").

I've tested it with data that (I think) is in the same format as yours:
![before](https://user-images.githubusercontent.com/44614829/166296238-3c9de88c-8e37-4955-b369-9df2fcc4da8b.png)
(The transform there is just to get the *row* field to be of type *string*.  Yours already is a string)

Like in your example, this doesn't work: No *breakdown* field is found.

After adding the "Prepare time series" transform, the *breakdown* field is found:
![after](https://user-images.githubusercontent.com/44614829/166296543-4f673a73-4fea-49c8-9b49-9c29f94e05b8.png)
 
 And the plot looks as expected for that data:
![example](https://user-images.githubusercontent.com/44614829/166296624-27d5cf79-8f02-4ae1-8387-ea04cc07a6fd.png)


While I believe this solve your use case (let me know if it doesn't), I completely agree that the documentation isn't clear around this topic, which is definitely very frustrating for users.  I'll update the docs to make it clearer.

Also, I'll work on the plugin to make it able to work on data like this without the need for the "Prepare time series" transform.

**Comment by boazreicher** [comment]
Updated the docs to highlight this issue: [here](https://boazreicher.github.io/mosaic-plot/data/#1-regular-data-format)

**Comment by boazreicher** [comment]
Hi @Sejsel, 
I've added a new data format `Single Frame` (also `Regular` is renamed to `Multi Frame`):
![ex_singleframe](https://user-images.githubusercontent.com/44614829/168055879-e4dd1b5d-de20-46b3-a416-3b2fd026a022.png)

Using this data format should work well with your use case, without requiring any transforms (I've also made a change to support both *string* and *number* fields/labels as the `Breakdown` or `Group` fields)

This [release](https://github.com/boazreicher/mosaic-plot/releases/tag/v1.0.11) has all of the changes.

Before I update the docs and publish the new version to Grafana Marketplace, would you mind testing it and confirming that is solves your issue?

Thanks,

**Comment by boazreicher** [comment]
Fixed in [v1.0.13](https://github.com/boazreicher/mosaic-plot/releases/tag/v1.0.13)
Updated [docs](https://boazreicher.github.io/mosaic-plot/data/)
Updated in Grafana Marketplace.
