### ISSUE TITLE
Feature Request: Ignore Null Values

### ISSUE THREAD

**Issue by andybaumgar** [boazreicher/mosaic-plot#5]
Hi, thanks for the great plugin!  

It appears that null values are currently rendered as if they are 0.  It would be great if there was an option to render entirely null regions as transparent, and for mixed regions to ignore null in the average.

In my application many intervals have no data, so this feature would be very useful.  If you are open to PR's I could take a shot at implementing the feature.

Thanks again!

**Comment by boazreicher** [comment]
Hi @andybaumgar 👋 
The panel treats missing values as 0 by default, but you can change that with the [Zero Values](https://boazreicher.github.io/mosaic-plot/configuration_options/#style) configuration option (render as transparent, or not render the cell at all).
Here's an example:
https://github.com/boazreicher/mosaic-plot/assets/44614829/4a1866f0-2332-4400-88cc-60d3fe7efa15

Regarding how average values are computed when there are null values - you're right.  Those are treated as 0 (so no effect on `sum`, but it could lead to incorrect results for `avg`)
It would be great if you could open a PR to fix that.  I believe the fix should be in https://github.com/boazreicher/mosaic-plot/blob/main/src/data/SeriesUtils.tsx#L288 (calculate how many null values are in each bin, and then subtract them from the denominator in `aggregated = sum / binSize;`).  I think that behavior should depend on the value of the [Zero Values](https://boazreicher.github.io/mosaic-plot/configuration_options/#style) setting (sometimes it might make sense to treat null values as zeros in the average, and sometimes it can make sense to disregard them)

**Comment by andybaumgar** [comment]
Thanks @boazreicher!  I had been using zero to represent a discrete "no error" state, but I should be able to encode it to something else.

I'll start the PR for ignoring null in the average.  At the very least I am curious to see how your plugin works :)

**Comment by boazreicher** [comment]
Hi @andybaumgar, I've created a new release (https://github.com/boazreicher/mosaic-plot/releases/tag/v1.0.18) with your changes.  I've also submitted it to Grafana for review.  I'll post an update here once the new version gets published in the Grafana Marketplace.

**Comment by andybaumgar** [comment]
Woo!

**Comment by boazreicher** [comment]
@andybaumgar the plugin has been updated in the Grafana Marketplace:


![Image](https://github.com/boazreicher/mosaic-plot/assets/44614829/b90296f3-0a03-4f95-b030-d20bf7c9b66c)

**Comment by andybaumgar** [comment]
Awesome!  I'll update my dashboard :)
